name: Deploy to Server with Tests

on:
  push:
    branches: [ main]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/final-devops-app:latest

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/final-devops-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /opt/app
            sudo docker compose pull && sudo docker compose up -d --force-recreate