name: Deploy to AWS with Tests

on:
  push:
    branches:
      # - main
        - orbach/gitHub-WorkFlows
  workflow_dispatch: # accept manual trigger
    inputs:
      confirm_deploy:
        description: 'server deployment'
        required: true
        default: 'NO' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Run linting
        run: npm run lint

      - name: Start React app for testing
        run: npm run preview &
        env:
          CI: true

      - name: Wait for app to start
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:4173; do sleep 2; done'
          echo "App is running!"

      - name: Set up Python for Selenium
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Selenium dependencies
        run: |
          cd selenium
          pip install -r requirements.txt

      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@latest

      - name: Update Selenium config for CI
        run: |
          cd selenium
          echo '{"url": "http://localhost:4173", "holiday_types": ["jewish", "muslim", "christian"]}' > config.json

      - name: Run Selenium Tests
        run: |
          cd selenium
          python testHeadless.py
        timeout-minutes: 5

      - name: Stop React app
        run: pkill -f "vite preview" || true

      - name: Set up Python for Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          pip install ansible boto boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ansible-playbook ansible/deploy_server_app.yml --ssh-common-args='-o StrictHostKeyChecking=no' \
            -e "docker_user=${{ secrets.DOCKER_USER }}" \
            -e "docker_token=${{ secrets.DOCKER_TOKEN }}"
