name: Test Build Only (No Deploy)

on:
  workflow_dispatch:  # ניתן להפעיל ידנית
  push:
    branches:
      - orbach/gitHub-WorkFlows  # רק על הענף הנוכחי

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Run linting
        run: npm run lint

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          pip install ansible boto boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Validate Ansible Syntax
        run: |
          ansible-playbook --syntax-check ansible/deploy_server_app.yml

      - name: Test Complete
        run: echo "✅ All tests passed! Ready for deployment."
